arkNetwork:
  name: testnet
  scheme: http

ethBridge:
  ethServerUrl: http://localhost:8545
  scriptPath: ./bin
  nodeCommand: /usr/local/bin/node

  serviceArkWallet:
    address: todo
    passphrase: hello
    passphrase2: world

  serviceEthAccount:
    address: todo
    password: 12345
